import { useRouter } from 'next/router';
import Head from 'next/head';
import { Inter } from '@next/font/google';

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const router = useRouter();
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1>Welcome to Rick & Morty webapp</h1>
        <p>Bla bla bla</p>
        <button onClick={()=>router.push('/characters/1')}>Browse Characters</button>
      </main>
    </>
  )
}
