import { useRouter } from 'next/router';
import Head from 'next/head';
import { Container, LoginCard, FieldContainer, SubmitButton } from '../styles/register.styled';


export default function Register() {
  const router = useRouter();

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Container>
          <LoginCard>
            <h3>Login</h3>
            <FieldContainer>
              <label>Email</label>
              <input type="email" />
              <span>Error message</span>
            </FieldContainer>
            <FieldContainer>
              <label>Password</label>
              <input type="password" />
              <span>Error message</span>
            </FieldContainer>
            <FieldContainer>
              <label>Repeat Password</label>
              <input type="password" />
              <span>Error message</span>
            </FieldContainer>
            <SubmitButton onClick={() => router.push('/dashboard')}>Login</SubmitButton>
          </LoginCard>
        </Container>
      </main>
    </>
  )
}
